### ISSUE TITLE
Regression test failure on big-endian

### ISSUE THREAD

**Issue by df7cb** [darold/pgtt#49]
On big-endian s390x Debian bookworm+bullseye and Ubuntu noble I'm seeing regression diffs:

```
14:01:02 **** regression.diffs ****
14:01:02 diff -U3 /<<PKGBUILDDIR>>/test/expected/01_oncommitdelete.out /<<PKGBUILDDIR>>/results/01_oncommitdelete.out
14:01:02 --- /<<PKGBUILDDIR>>/test/expected/01_oncommitdelete.out	2024-05-31 02:58:35.000000000 +0000
14:01:02 +++ /<<PKGBUILDDIR>>/results/01_oncommitdelete.out	2024-06-04 12:01:00.734117902 +0000
14:01:02 @@ -108,7 +108,8 @@
14:01:02  
14:01:02  -- The "template" unlogged table should not exists anymore
14:01:02  SELECT n.nspname, c.relname FROM pg_class c JOIN pg_namespace n ON (c.relnamespace=n.oid) WHERE relname = 't_glob_temptable1';
14:01:02 - nspname | relname 
14:01:02 ----------+---------
14:01:02 -(0 rows)
14:01:02 +  nspname  |      relname      
14:01:02 +-----------+-------------------
14:01:02 + pg_temp_3 | t_glob_temptable1
14:01:02 +(1 row)
14:01:02  
14:01:02 diff -U3 /<<PKGBUILDDIR>>/test/expected/11_after_error.out /<<PKGBUILDDIR>>/results/11_after_error.out
14:01:02 --- /<<PKGBUILDDIR>>/test/expected/11_after_error.out	2024-05-31 02:58:35.000000000 +0000
14:01:02 +++ /<<PKGBUILDDIR>>/results/11_after_error.out	2024-06-04 12:01:02.494027736 +0000
14:01:02 @@ -89,7 +89,8 @@
14:01:02  
14:01:02  -- The "template" unlogged table should not exists anymore
14:01:02  SELECT n.nspname, c.relname FROM pg_class c JOIN pg_namespace n ON (c.relnamespace=n.oid) WHERE relname = 't_glob_temptable1';
14:01:02 - nspname | relname 
14:01:02 ----------+---------
14:01:02 -(0 rows)
14:01:02 +  nspname  |      relname      
14:01:02 +-----------+-------------------
14:01:02 + pg_temp_3 | t_glob_temptable1
14:01:02 +(1 row)
14:01:02  
```

It seems to be randomly failing independently from the PG version, I've seen failures on PG16 and 15.

Other architectures seem unaffected.

Full build logs: https://pgdgbuild.dus.dg-i.net/job/pgtt-binaries/3/

**Comment by rjuju** [comment]
Hi Christoph,

thanks for the report.  The issue is quite surprising, If I understand correctly it means that the template table is removed as expected, but also that an associated temporary table still exists.  I don't really see how the temporary table could have been created in a new session that doesn't try to use it, especially since the code explicitly prevent such scenario and the associated test doesn't fail.  One theory could be that a previous temporary from an earlier session survived for some reason, but that shouldn't be possible either, and while I don't know much about the s390x architecture (or the associated specific code) it seems unlikely to be specific for that too.

Maybe @darold has an idea.

**Comment by darold** [comment]
Hi @df7cb,

Can you give a try to latest development code, commit 9323178 might solve this issue. Look like the temporary table record in pg_class is removed from pg_class asynchronously by autovaccum or some other mechnism. I had already the same problem in test 08_plplgsql.sql

**Comment by df7cb** [comment]
That fixed it: https://pgdgbuild.dus.dg-i.net/job/pgtt-binaries/4/

Merci bien!
